export const PS4_LIBRARY = [

  // 1. Define the library locally (removed 'export')

  /* PASTE YOUR FULL 1000+ LIST HERE */ 
  { title: "Ghost of Tsushima", studio: "Sucker Punch" },
  { title: "Ghost of Tsushima", studio: "Sucker Punch" },
{ title: "Ghost of Tsushima", studio: "Sucker Punch", estPrice: 8500 },
  { title: "Red Dead Redemption 2", studio: "Rockstar Games", estPrice: 7500 },
  { title: "The Last of Us Part II", studio: "Naughty Dog", estPrice: 6500 },
  { title: "Grand Theft Auto V", studio: "Rockstar North", estPrice: 6000 },
  { title: "The Witcher 3: Wild Hunt", studio: "CD Projekt Red", estPrice: 5500 },
  { title: "Horizon Zero Dawn", studio: "Guerrilla Games", estPrice: 4500 },

  // --- SPORTS & COMBAT ---
  { title: "FIFA 23", studio: "EA Sports", estPrice: 5500 },
  { title: "UFC 4", studio: "EA Sports", estPrice: 6500 },
  { title: "UFC 3", studio: "EA Sports", estPrice: 4000 },
  { title: "NBA 2K17", studio: "Visual Concepts", estPrice: 1500 }, // Legacy sports value
  { title: "FIFA 19", studio: "EA Sports", estPrice: 2500 }, // Legacy sports value

  // --- SHOOTERS & ACTION ---
  { title: "Call of Duty: WW2", studio: "Sledgehammer Games", estPrice: 4500 },
  { title: "Call of Duty: Black Ops 4", studio: "Treyarch", estPrice: 4000 },
  { title: "Call of Duty: Infinite Warfare", studio: "Infinity Ward", estPrice: 3000 },
  { title: "Battlefield 1", studio: "DICE", estPrice: 3500 },
  { title: "Ghost Recon Breakpoint", studio: "Ubisoft", estPrice: 5500 },
  { title: "Ghost Recon Wildlands", studio: "Ubisoft", estPrice: 3500 },
  { title: "Watch Dogs 2", studio: "Ubisoft", estPrice: 3000 },
  { title: "Assassin's Creed IV: Black Flag", studio: "Ubisoft", estPrice: 3000 },
  { title: "Tom Clancy's The Division", studio: "Ubisoft", estPrice: 2500 },
  { title: "For Honor", studio: "Ubisoft Montreal", estPrice: 2500 },

  // --- LEGACY & CLASSICS ---
  { title: "Uncharted 4: A Thief's End", studio: "Naughty Dog", estPrice: 3500 },
  { title: "The Last of Us Remastered", studio: "Naughty Dog", estPrice: 3000 },
  { title: "Spider-Man", studio: "Insomniac Games", estPrice: 5000 },
    { title: "Tom Clancy's Ghost Recon Breakpoint", studio: "Ubisoft", estPrice: 4500 },
  { title: "Ghost of Tsushima", studio: "Sucker Punch", estPrice: 8500 },
{ title: "God of War", studio: "Santa Monica Studio", estPrice: 7500 },
  { title: "The Last of Us Part II", studio: "Naughty Dog" },
  { title: "Uncharted 4: A Thief's End", studio: "Naughty Dog" },
  { title: "Spider-Man", studio: "Insomniac Games" },
  { title: "Red Dead Redemption 2", studio: "Rockstar Games" },
  { title: "Bloodborne", studio: "FromSoftware" },
  { title: "Horizon Zero Dawn", studio: "Guerrilla Games" },
  { title: "Elden Ring", studio: "FromSoftware" },
  { title: "Grand Theft Auto V", studio: "Rockstar North" },
  { title: "The Witcher 3: Wild Hunt", studio: "CD Projekt Red" },
  { title: "Final Fantasy VII Remake", studio: "Square Enix" },
  { title: "Persona 5 Royal", studio: "Atlus" },
  { title: "Ratchet & Clank", studio: "Insomniac Games" },
  { title: "Days Gone", studio: "Bend Studio" },
  { title: "Detroit: Become Human", studio: "Quantic Dream" },
  { title: "Infamous Second Son", studio: "Sucker Punch" },
  { title: "Ghost Recon Wildlands", studio: "Ubisoft" },
  { title: "The Order: 1886", studio: "Ready at Dawn" },
  { title: "Batman: Arkham Knight", studio: "Rocksteady" },
  { title: "Cyberpunk 2077", studio: "CD Projekt Red" },
  { title: "Assassin's Creed Valhalla", studio: "Ubisoft" },
  { title: "Assassin's Creed Odyssey", studio: "Ubisoft" },
  { title: "Assassin's Creed Origins", studio: "Ubisoft" },
  { title: "Sekiro: Shadows Die Twice", studio: "FromSoftware" },
  { title: "Dark Souls III", studio: "FromSoftware" },
  { title: "Dark Souls Remastered", studio: "FromSoftware" },
  { title: "Resident Evil 2", studio: "Capcom" },
  { title: "Resident Evil 3", studio: "Capcom" },
  { title: "Resident Evil 7: Biohazard", studio: "Capcom" },
  { title: "Resident Evil Village", studio: "Capcom" },
  { title: "Devil May Cry 5", studio: "Capcom" },
  { title: "Monster Hunter: World", studio: "Capcom" },
  { title: "Death Stranding", studio: "Kojima Productions" },
  { title: "Metal Gear Solid V: The Phantom Pain", studio: "Kojima Productions" },
  { title: "Nioh", studio: "Team Ninja" },
  { title: "Nioh 2", studio: "Team Ninja" },
  { title: "Ghost of Tsushima: Director's Cut", studio: "Sucker Punch" },
  { title: "Sifu", studio: "Sloclap" },
  { title: "Mortal Kombat 11", studio: "NetherRealm Studios" },
  { title: "Injustice 2", studio: "NetherRealm Studios" },
  { title: "Tekken 7", studio: "Bandai Namco" },
  { title: "Street Fighter V", studio: "Capcom" },
  { title: "Dragon Ball FighterZ", studio: "Arc System Works" },
  { title: "Guilty Gear Strive", studio: "Arc System Works" },
  { title: "Gran Turismo Sport", studio: "Polyphony Digital" },
  { title: "Need for Speed Heat", studio: "Ghost Games" },
  { title: "F1 2021", studio: "Codemasters" },
  { title: "Dirt 5", studio: "Codemasters" },
  { title: "Star Wars Jedi: Fallen Order", studio: "Respawn Entertainment" },
  { title: "Apex Legends", studio: "Respawn Entertainment" },
  { title: "Titanfall 2", studio: "Respawn Entertainment" },
  { title: "Call of Duty: Modern Warfare", studio: "Infinity Ward" },
  { title: "Call of Duty: Black Ops Cold War", studio: "Treyarch" },
  { title: "Call of Duty: Warzone", studio: "Raven Software" },
  { title: "Battlefield V", studio: "DICE" },
  { title: "Battlefield 1", studio: "DICE" },
  { title: "Overwatch", studio: "Blizzard Entertainment" },
  { title: "Diablo III: Eternal Collection", studio: "Blizzard Entertainment" },
  { title: "Doom Eternal", studio: "id Software" },
  { title: "Doom (2016)", studio: "id Software" },
  { title: "Wolfenstein II: The New Colossus", studio: "MachineGames" },
  { title: "Dishonored 2", studio: "Arkane Studios" },
  { title: "Prey", studio: "Arkane Studios" },
  { title: "Fallout 4", studio: "Bethesda Game Studios" },
  { title: "The Elder Scrolls V: Skyrim SE", studio: "Bethesda Game Studios" },
  { title: "Mass Effect Legendary Edition", studio: "BioWare" },
  { title: "Dragon Age: Inquisition", studio: "BioWare" },
  { title: "Control", studio: "Remedy Entertainment" },
  { title: "Alan Wake Remastered", studio: "Remedy Entertainment" },
  { title: "Hitman 3", studio: "IO Interactive" },
  { title: "Tomb Raider: Definitive Edition", studio: "Crystal Dynamics" },
  { title: "Rise of the Tomb Raider", studio: "Crystal Dynamics" },
  { title: "Shadow of the Tomb Raider", studio: "Eidos-Montréal" },
  { title: "Marvel's Guardians of the Galaxy", studio: "Eidos-Montréal" },
  { title: "Deus Ex: Mankind Divided", studio: "Eidos-Montréal" },
  { title: "Just Cause 4", studio: "Avalanche Studios" },
  { title: "Mad Max", studio: "Avalanche Studios" },
  { title: "Far Cry 6", studio: "Ubisoft" },
  { title: "Far Cry 5", studio: "Ubisoft" },
  { title: "Far Cry 4", studio: "Ubisoft" },
  { title: "Watch Dogs: Legion", studio: "Ubisoft" },
  { title: "Watch Dogs 2", studio: "Ubisoft" },
  { title: "Tom Clancy's The Division 2", studio: "Ubisoft" },
  { title: "Rainbow Six Siege", studio: "Ubisoft" },
  { title: "Rayman Legends", studio: "Ubisoft" },
  { title: "Life is Strange", studio: "Dontnod Entertainment" },
  { title: "Life is Strange 2", studio: "Dontnod Entertainment" },
  { title: "Vampyr", studio: "Dontnod Entertainment" },
  { title: "Kingdom Hearts III", studio: "Square Enix" },
  { title: "NieR: Automata", studio: "PlatinumGames" },
  { title: "NieR Replicant ver.1.22", studio: "Toylogic" },
  { title: "Bayonetta & Vanquish", studio: "PlatinumGames" },
  { title: "Yakuza 0", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza: Like a Dragon", studio: "Ryu Ga Gotoku Studio" },
  { title: "Judgment", studio: "Ryu Ga Gotoku Studio" },
  { title: "Lost Judgment", studio: "Ryu Ga Gotoku Studio" },
  { title: "Fist of the North Star: Lost Paradise", studio: "Ryu Ga Gotoku Studio" },
  { title: "Persona 5 Strikers", studio: "Omega Force" },
  { title: "Dynasty Warriors 9", studio: "Omega Force" },
  { title: "Hades", studio: "Supergiant Games" },
  { title: "Bastion", studio: "Supergiant Games" },
  { title: "Transistor", studio: "Supergiant Games" },
  { title: "Hollow Knight", studio: "Team Cherry" },
  { title: "Cuphead", studio: "Studio MDHR" },
  { title: "Celeste", studio: "Extremely OK Games" },
  { title: "Stardew Valley", studio: "ConcernedApe" },
  { title: "Undertale", studio: "tobyfox" },
  { title: "Subnautica", studio: "Unknown Worlds" },
  { title: "The Forest", studio: "Endnight Games" },
  { title: "No Man's Sky", studio: "Hello Games" },
  { title: "Rocket League", studio: "Psyonix" },
  { title: "Fall Guys", studio: "Mediatonic" },
  { title: "Genshin Impact", studio: "miHoYo" },
  { title: "Destiny 2", studio: "Bungie" },
  { title: "Warframe", studio: "Digital Extremes" },
  { title: "The Last Guardian", studio: "Japan Studio" },
  { title: "Shadow of the Colossus", studio: "Bluepoint Games" },
  { title: "Gravity Rush Remastered", studio: "Japan Studio" },
  { title: "Gravity Rush 2", studio: "Japan Studio" },
  { title: "Knack II", studio: "Japan Studio" },
  { title: "Concrete Genie", studio: "Pixelopus" },
  { title: "MediEvil", studio: "Other Ocean Emeryville" },
  { title: "Sackboy: A Big Adventure", studio: "Sumo Digital" },
  { title: "LittleBigPlanet 3", studio: "Sumo Digital" },
  { title: "Dreams", studio: "Media Molecule" },
  { title: "Tearaway Unfolded", studio: "Media Molecule" },
  { title: "Crash Bandicoot N. Sane Trilogy", studio: "Vicarious Visions" },
  { title: "Crash Bandicoot 4: It's About Time", studio: "Toys for Bob" },
  { title: "Spyro Reignited Trilogy", studio: "Toys for Bob" },
  { title: "Tony Hawk's Pro Skater 1 + 2", studio: "Vicarious Visions" },
  { title: "Minecraft", studio: "Mojang Studios" },
  { title: "Terraria", studio: "Re-Logic" },
  { title: "Ark: Survival Evolved", studio: "Studio Wildcard" },
  { title: "Rust", studio: "Facepunch Studios" },
  { title: "DayZ", studio: "Bohemia Interactive" },
  { title: "Outer Wilds", studio: "Mobius Digital" },
  { title: "What Remains of Edith Finch", studio: "Giant Sparrow" },
  { title: "Journey", studio: "thatgamecompany" },
  { title: "Abzû", studio: "Giant Squid" },
  { title: "Firewatch", studio: "Campo Santo" },
  { title: "Inside", studio: "Playdead" },
  { title: "Limbo", studio: "Playdead" },
  { title: "Little Nightmares", studio: "Tarsier Studios" },
  { title: "Little Nightmares II", studio: "Tarsier Studios" },
  { title: "It Takes Two", studio: "Hazelight Studios" },
  { title: "A Way Out", studio: "Hazelight Studios" },
  { title: "Dead by Daylight", studio: "Behaviour Interactive" },
  { title: "Friday the 13th: The Game", studio: "IllFonic" },
  { title: "Predator: Hunting Grounds", studio: "IllFonic" },
  { title: "Alien: Isolation", studio: "Creative Assembly" },
  { title: "The Evil Within", studio: "Tango Gameworks" },
  { title: "The Evil Within 2", studio: "Tango Gameworks" },
  { title: "Outlast", studio: "Red Barrels" },
  { title: "Outlast 2", studio: "Red Barrels" },
  { title: "Amnesia: Collection", studio: "Frictional Games" },
  { title: "SOMA", studio: "Frictional Games" },
  { title: "Layers of Fear", studio: "Bloober Team" },
  { title: "The Medium", studio: "Bloober Team" },
  { title: "Observation", studio: "No Code" },
  { title: "Returnal", studio: "Housemarque" },
  { title: "Nex Machina", studio: "Housemarque" },
  { title: "Resogun", studio: "Housemarque" },
  { title: "Alienation", studio: "Housemarque" },
  { title: "Matterfall", studio: "Housemarque" },
  { title: "Dead Nation: Apocalypse Edition", studio: "Housemarque" },
  { title: "The Binding of Isaac: Rebirth", studio: "Nicalis" },
  { title: "Enter the Gungeon", studio: "Dodge Roll" },
  { title: "Dead Cells", studio: "Motion Twin" },
  { title: "Rogue Legacy 2", studio: "Cellar Door Games" },
  { title: "Spelunky 2", studio: "Mossmouth" },
  { title: "Slay the Spire", studio: "MegaCrit" },
  { title: "Risk of Rain 2", studio: "Hopoo Games" },
  { title: "Remnant: From the Ashes", studio: "Gunfire Games" },
  { title: "World War Z", studio: "Saber Interactive" },
  { title: "SnowRunner", studio: "Saber Interactive" },
  { title: "MudRunner", studio: "Saber Interactive" },
  { title: " Farming Simulator 22", studio: "Giants Software" },
  { title: "The Sims 4", studio: "Maxis" },
  { title: "Cities: Skylines", studio: "Colossal Order" },
  { title: "Tropico 6", studio: "Limbic Entertainment" },
  { title: "Jurassic World Evolution", studio: "Frontier Developments" },
  { title: "Planet Coaster", studio: "Frontier Developments" },
  { title: "Elite Dangerous", studio: "Frontier Developments" },
  { title: "Kerbal Space Program", studio: "Squad" },
  { title: "XCOM 2", studio: "Firaxis Games" },
  { title: "Sid Meier's Civilization VI", studio: "Firaxis Games" },
  { title: "Divinity: Original Sin 2", studio: "Larian Studios" },
  { title: "Path of Exile", studio: "Grinding Gear Games" },
  { title: "Warhammer: Vermintide 2", studio: "Fatshark" },
  { title: "Deep Rock Galactic", studio: "Ghost Ship Games" },
  { title: "Hotline Miami", studio: "Dennaton Games" },
  { title: "Katana ZERO", studio: "Askiisoft" },
  { title: "My Friend Pedro", studio: "DeadToast Entertainment" },
  { title: "Superhot", studio: "Superhot Team" },
  { title: "Ghostrunner", studio: "One More Level" },
  { title: "Absolver", studio: "Sloclap" },
  { title: "Sleeping Dogs: Definitive Edition", studio: "United Front Games" },
  { title: "Mafia: Definitive Edition", studio: "Hangar 13" },
  { title: "Mafia II: Definitive Edition", studio: "Hangar 13" },
  { title: "Mafia III: Definitive Edition", studio: "Hangar 13" },
  { title: "L.A. Noire", studio: "Team Bondi" },
  { title: "Bully: Scholarship Edition", studio: "Rockstar Games" },
  { title: "Manhunt", studio: "Rockstar North" },
  { title: "The Warriors", studio: "Rockstar Toronto" },

  // --- JRPGs & ANIME STYLED ---
  { title: "Tales of Arise", studio: "Bandai Namco" },
  { title: "Tales of Berseria", studio: "Bandai Namco" },
  { title: "Scarlet Nexus", studio: "Bandai Namco" },
  { title: "Code Vein", studio: "Bandai Namco" },
  { title: "Ni no Kuni: Wrath of the White Witch", studio: "Level-5" },
  { title: "Ni no Kuni II: Revenant Kingdom", studio: "Level-5" },
  { title: "Dragon Quest XI: Echoes of an Elusive Age", studio: "Square Enix" },
  { title: "Trials of Mana", studio: "Square Enix" },
  { title: "Octopath Traveler II", studio: "Square Enix" },
  { title: "Star Ocean: The Divine Force", studio: "tri-Ace" },
  { title: "Shin Megami Tensei III Nocturne HD", studio: "Atlus" },
  { title: "Soul Hackers 2", studio: "Atlus" },
  { title: "Catherine: Full Body", studio: "Atlus" },
  { title: "Sakura Wars", studio: "Sega" },
  { title: "The Legend of Heroes: Trails of Cold Steel", studio: "Nihon Falcom" },
  { title: "Ys VIII: Lacrimosa of Dana", studio: "Nihon Falcom" },
  { title: "Ys IX: Monstrum Nox", studio: "Nihon Falcom" },
  { title: "Granblue Fantasy: Versus", studio: "Arc System Works" },

  // --- FIGHTING & MARTIAL ARTS ---
  { title: "UFC 4", studio: "EA Sports" },
  { title: "UFC 3", studio: "EA Sports" },
  { title: "WWE 2K22", studio: "Visual Concepts" },
  { title: "SoulCalibur VI", studio: "Bandai Namco" },
  { title: "Dead or Alive 6", studio: "Team Ninja" },
  { title: "Virtua Fighter 5 Ultimate Showdown", studio: "Sega" },
  { title: "Samurai Shodown", studio: "SNK" },
  { title: "The King of Fighters XV", studio: "SNK" },
  { title: "BlazBlue: Cross Tag Battle", studio: "Arc System Works" },
  { title: "Brawlhalla", studio: "Blue Mammoth Games" },

  // --- SHOOTERS & ACTION ---
  { title: "Wolfenstein: The New Order", studio: "MachineGames" },
  { title: "Wolfenstein: The Old Blood", studio: "MachineGames" },
  { title: "Sniper Elite 5", studio: "Rebellion" },
  { title: "Sniper Elite 4", studio: "Rebellion" },
  { title: "Zombie Army 4: Dead War", studio: "Rebellion" },
  { title: "Hunt: Showdown", studio: "Crytek" },
  { title: "Crysis Remastered", studio: "Crytek" },
  { title: "Metro Exodus", studio: "4A Games" },
  { title: "Metro Redux", studio: "4A Games" },
  { title: "Rage 2", studio: "Avalanche Studios" },
  { title: "Just Cause 3", studio: "Avalanche Studios" },
  { title: "Borderlands 3", studio: "Gearbox Software" },
  { title: "Borderlands: The Handsome Collection", studio: "Gearbox Software" },
  { title: "Tiny Tina's Wonderlands", studio: "Gearbox Software" },
  { title: "The Outer Worlds", studio: "Obsidian Entertainment" },
  { title: "Remnant 2", studio: "Gunfire Games" },

  // --- HORROR & THRILLER ---
  { title: "Until Dawn: Rush of Blood", studio: "Supermassive Games" },
  { title: "The Quarry", studio: "Supermassive Games" },
  { title: "The Dark Pictures Anthology: Man of Medan", studio: "Supermassive" },
  { title: "The Dark Pictures Anthology: Little Hope", studio: "Supermassive" },
  { title: "The Dark Pictures Anthology: House of Ashes", studio: "Supermassive" },
  { title: "The Dark Pictures Anthology: The Devil in Me", studio: "Supermassive" },
  { title: "Daylight", studio: "Zombie Studios" },
  { title: "Home Sweet Home", studio: "YGGDRAZIL Group" },
  { title: "White Day: A Labyrinth Named School", studio: "Sonnori" },
  { title: "Fatal Frame: Maiden of Black Water", studio: "Koei Tecmo" },
  { title: "Tormented Souls", studio: "Dual Effect" },

  // --- INDIE & PUZZLE ---
  { title: "Outer Wilds", studio: "Mobius Digital" },
  { title: "Tunic", studio: "Andrew Shouldice" },
  { title: "Death's Door", studio: "Acid Nerve" },
  { title: "Twelve Minutes", studio: "Luis Antonio" },
  { title: "The Witness", studio: "Thekla, Inc." },
  { title: "The Talos Principle", studio: "Croteam" },
  { title: "Superliminal", studio: "Pillow Castle" },
  { title: "Viewfinder", studio: "Sad Owl Studios" },
  { title: "Cocoon", studio: "Geometric Interactive" },
  { title: "Stray", studio: "BlueTwelve Studio" },
  { title: "Kena: Bridge of Spirits", studio: "Ember Lab" },
  { title: "Sable", studio: "Shedworks" },
  { title: "Solar Ash", studio: "Heart Machine" },
  { title: "Hyper Light Drifter", studio: "Heart Machine" },
  { title: "Furi", studio: "The Game Bakers" },

  // --- PLATFORMERS & CLASSICS ---
  { title: "Sonic Frontiers", studio: "Sonic Team" },
  { title: "Sonic Mania", studio: "PagodaWest Games" },
  { title: "Sonic Forces", studio: "Sonic Team" },
  { title: "Rayman Origins", studio: "Ubisoft" },
  { title: "Mega Man 11", studio: "Capcom" },
  { title: "Mega Man Legacy Collection", studio: "Capcom" },
  { title: "Castlevania Requiem", studio: "Konami" },
  { title: "Castlevania Advance Collection", studio: "Konami" },
  { title: "Contra: Rogue Corps", studio: "Konami" },
  { title: "Ghosts 'n Goblins Resurrection", studio: "Capcom" },
  { title: "Wonder Boy: The Dragon's Trap", studio: "Lizardcube" },
  { title: "Streets of Rage 4", studio: "Dotemu" },
  { title: "Teenage Mutant Ninja Turtles: Shredder's Revenge", studio: "Tribute Games" },

  // --- SPORTS & RACING ---
  { title: "FIFA 23", studio: "EA Sports" },
  { title: "FIFA 22", studio: "EA Sports" },
  { title: "Madden NFL 23", studio: "EA Tiburon" },
  { title: "NBA 2K23", studio: "Visual Concepts" },
  { title: "MLB The Show 22", studio: "San Diego Studio" },
  { title: "Tony Hawk's Underground", studio: "Neversoft" },
  { title: "Skater XL", studio: "Easy Day Studios" },
  { title: "Session: Skate Sim", studio: "cre-ā-ture Studios" },
  { title: "Hot Wheels Unleashed", studio: "Milestone" },
  { title: "Ride 4", studio: "Milestone" },
  { title: "MotoGP 22", studio: "Milestone" },
  { title: "Wreckfest", studio: "Bugbear Entertainment" },
  { title: "Project CARS 3", studio: "Slightly Mad Studios" },
  { title: "Assetto Corsa Competizione", studio: "Kunos Simulazioni" },

  // --- SIMULATION & STRATEGY ---
  { title: "The Sims 4", studio: "Maxis" },
  { title: "Two Point Hospital", studio: "Two Point Studios" },
  { title: "Two Point Campus", studio: "Two Point Studios" },
  { title: "Prison Architect", studio: "Introversion Software" },
  { title: "Kerbal Space Program Enhanced Edition", studio: "Squad" },
  { title: "Surviving Mars", studio: "Haemimont Games" },
  { title: "Frostpunk", studio: "11 bit studios" },
  { title: "This War of Mine: The Little Ones", studio: "11 bit studios" },
  { title: "Ancestors: The Humankind Odyssey", studio: "Panache Digital Games" },
  { title: "Desperados III", studio: "Mimimi Games" },
  { title: "Shadow Tactics: Blades of the Shogun", studio: "Mimimi Games" },
  { title: "Mutant Year Zero: Road to Eden", studio: "The Bearded Ladies" },

  // --- ADVENTURE & STORY ---
  { title: "Oxenfree", studio: "Night School Studio" },
  { title: "Oxenfree II: Lost Signals", studio: "Night School Studio" },
  { title: "Kentucky Route Zero", studio: "Cardboard Computer" },
  { title: "Night in the Woods", studio: "Infinite Fall" },
  { title: "A Short Hike", studio: "Adamgryu" },
  { title: "Gris", studio: "Nomada Studio" },
  { title: "Spiritfarer", studio: "Thunder Lotus Games" },
  { title: "The Artful Escape", studio: "Beethoven & Dinosaur" },
  { title: "Disco Elysium", studio: "ZA/UM" },

  // --- REMAINING LIST (VARIETY) ---
  { title: "Vampire: The Masquerade - Bloodhunt", studio: "Sharkmob" },
  { title: "Path of Exile", studio: "Grinding Gear Games" },
  { title: "Warface", studio: "Crytek" },
  { title: "Paladins", studio: "Hi-Rez Studios" },
  { title: "Smite", studio: "Hi-Rez Studios" },
  { title: "Enlisted", studio: "Darkflow Software" },
  { title: "H1Z1: Battle Royale", studio: "Daybreak Game Company" },
  { title: "Let It Die", studio: "Grasshopper Manufacture" },
  { title: "No More Heroes III", studio: "Grasshopper Manufacture" },
  { title: "Lollipop Chainsaw RePOP", studio: "Dragami Games" },
  { title: "Shadow Warrior 3", studio: "Flying Wild Hog" },
  { title: "Serious Sam 4", studio: "Croteam" },
  { title: "Telling Lies", studio: "Sam Barlow" },
  { title: "Her Story", studio: "Sam Barlow" },
  { title: "Immortality", studio: "Sam Barlow" },
  { title: "Outer Banks", studio: "Netflix Games" },
  { title: "PowerWash Simulator", studio: "FuturLab" },
  { title: "Gas Station Simulator", studio: "DRAGO entertainment" },
  { title: "Cooking Simulator", studio: "Big Cheese Studio" },
  { title: "Thief Simulator", studio: "Noble Muffins" },
  { title: "House Flipper", studio: "Empyrean" },
  { title: "Car Mechanic Simulator", studio: "Red Dot Games" },
  { title: "Bus Simulator 21", studio: "stillalive studios" },
  { title: "Construction Simulator", studio: "weltenbauer." },
  { title: "Train Sim World 3", studio: "Dovetail Games" },
  { title: "Microsoft Flight Simulator (PS Cloud)", studio: "Asobo Studio" },
  { title: "Slime Rancher", studio: "Monomi Park" },
  { title: "Grow: Song of the Evertree", studio: "Prideful Sloth" },
  { title: "Yonder: The Cloud Catcher Chronicles", studio: "Prideful Sloth" },
  { title: "A Hat in Time", studio: "Gears for Breakfast" },
  { title: "Bugsnax", studio: "Young Horses" },
  { title: "Octodad: Dadliest Catch", studio: "Young Horses" },
  { title: "Knockout City", studio: "Velan Studios" },
  { title: "Roller Champions", studio: "Ubisoft" },
  { title: "Riders Republic", studio: "Ubisoft" },
  { title: "The Crew 2", studio: "Ivory Tower" },
  { title: "The Crew Motorfest", studio: "Ivory Tower" },
  { title: "Steep", studio: "Ubisoft" },
  { title: "Trials Rising", studio: "RedLynx" },
  { title: "Evil West", studio: "Flying Wild Hog" },
  { title: "Trek to Yomi", studio: "Flying Wild Hog" },
  { title: "The Ascent", studio: "Neon Giant" },
  { title: "Ruiner", studio: "Reikon Games" },
  { title: "Eiyuden Chronicle: Rising", studio: "Rabbit & Bear Studios" },
  { title: "Bloodstained: Ritual of the Night", studio: "ArtPlay" },
  { title: "Indivisible", studio: "Lab Zero Games" },
  { title: "Skullgirls 2nd Encore", studio: "Lab Zero Games" },
  { title: "Granblue Fantasy: Relink", studio: "Cygames" },
  { title: "Danganronpa V3: Killing Harmony", studio: "Spike Chunsoft" },
  { title: "Zero Escape: The Nonary Games", studio: "Spike Chunsoft" },
  { title: "AI: The Somnium Files", studio: "Spike Chunsoft" },
  { title: "Digimon Story: Cyber Sleuth", studio: "Media.Vision" },
  { title: "Digimon Survive", studio: "Hyde" },
  { title: "One Piece: Pirate Warriors 4", studio: "Omega Force" },
  { title: "Naruto Shippuden: Ultimate Ninja Storm 4", studio: "CyberConnect2" },
  { title: "Dragon Ball Z: Kakarot", studio: "CyberConnect2" },
  { title: "JoJo's Bizarre Adventure: All Star Battle R", studio: "CyberConnect2" },
  { title: "Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles", studio: "CyberConnect2" },
  { title: "Jump Force", studio: "Spike Chunsoft" },
  { title: "Kill la Kill - If", studio: "Arc System Works" },
  { title: "Melty Blood: Type Lumina", studio: "French-Bread" },
  { title: "Under Night In-Birth Exe:Late[cl-r]", studio: "French-Bread" },
  { title: "BlazBlue: Central Fiction", studio: "Arc System Works" },
  { title: "Dead Cells: Return to Castlevania", studio: "Motion Twin" },
  { title: "Salt and Sanctuary", studio: "Ska Studios" },
  { title: "Salt and Sacrifice", studio: "Ska Studios" },
  { title: "Blasphemous", studio: "The Game Kitchen" },
  { title: "Blasphemous 2", studio: "The Game Kitchen" },
  { title: "The Last Case of Benedict Fox", studio: "Plot Twist" },
  { title: "Ender Lilies: Quietus of the Knights", studio: "Adglobe" },
  { title: "Vigil: The Longest Night", studio: "Glass Heart Games" },
  { title: "Grime", studio: "Clover Bite" },
  { title: "Moonscars", studio: "Black Mermaid" },
  { title: "Morbid: The Seven Acolytes", studio: "Still Running" },
  { title: "Hellpoint", studio: "Cradle Games" },
  { title: "The Surge", studio: "Deck13" },
  { title: "The Surge 2", studio: "Deck13" },
  { title: "Lords of the Fallen", studio: "Hexworks" },
  { title: "Mortal Shell", studio: "Cold Symmetry" },
  { title: "Thymesia", studio: "OverBorder Studio" },
  { title: "Steelrising", studio: "Spiders" },
  { title: "GreedFall", studio: "Spiders" },
  { title: "The Technomancer", studio: "Spiders" },
  { title: "Bound by Flame", studio: "Spiders" },
  { title: "ELEX", studio: "Piranha Bytes" },
  { title: "ELEX II", studio: "Piranha Bytes" },
  { title: "Kingdom Come: Deliverance", studio: "Warhorse Studios" },
    // --- ACTION & ADVENTURE (MODERN & RETRO) ---
  { title: "God of War III Remastered", studio: "Santa Monica Studio" },
  { title: "Shadow of the Beast", studio: "Heavy Spectrum" },
  { title: "MediEvil (2019)", studio: "Other Ocean" },
  { title: "The Last Guardian", studio: "Japan Studio" },
  { title: "The Pathless", studio: "Giant Squid" },
  { title: "Journey: Collector's Edition", studio: "Thatgamecompany" },
  { title: "Flower", studio: "Thatgamecompany" },
  { title: "Beyond: Two Souls", studio: "Quantic Dream" },
  { title: "Heavy Rain", studio: "Quantic Dream" },
  { title: "Indigo Prophecy", studio: "Quantic Dream" },
  { title: "Darksiders Warmastered Edition", studio: "Vigil Games" },
  { title: "Darksiders II Deathinitive Edition", studio: "Gunfire Games" },
  { title: "Darksiders III", studio: "Gunfire Games" },
  { title: "Darksiders Genesis", studio: "Airship Syndicate" },
  { title: "Okami HD", studio: "Clover Studio" },
  { title: "Mega Man 11", studio: "Capcom" },
  { title: "Mega Man X Legacy Collection", studio: "Capcom" },
  { title: "Disney Classic Games: Aladdin and The Lion King", studio: "Digital Eclipse" },
  { title: "Sonic Colors: Ultimate", studio: "Sega" },
  { title: "Sonic Team Racing", studio: "Sega" },

  // --- SHOOTERS & MILITARY ---
  { title: "Call of Duty: Vanguard", studio: "Sledgehammer Games" },
  { title: "Call of Duty: Modern Warfare II (2022)", studio: "Infinity Ward" },
  { title: "Call of Duty: WW2", studio: "Sledgehammer Games" },
  { title: "Call of Duty: Infinite Warfare", studio: "Infinity Ward" },
  { title: "Call of Duty: Ghosts", studio: "Infinity Ward" },
  { title: "Battlefield 2042", studio: "DICE" },
  { title: "Battlefield Hardline", studio: "Visceral Games" },
  { title: "Titanfall (Original)", studio: "Respawn" },
  { title: "Star Wars Battlefront", studio: "DICE" },
  { title: "Star Wars Battlefront II", studio: "DICE" },
  { title: "Star Wars: Squadrons", studio: "Motive Studio" },
  { title: "Doom 3: BFG Edition", studio: "id Software" },
  { title: "Quake Remastered", studio: "Nightdive Studios" },
  { title: "Quake II Remastered", studio: "Nightdive Studios" },
  { title: "Shadow Warrior", studio: "Flying Wild Hog" },
  { title: "Shadow Warrior 2", studio: "Flying Wild Hog" },
  { title: "Shadow Warrior 3: Definitive Edition", studio: "Flying Wild Hog" },
  { title: "Bulletstorm: Full Clip Edition", studio: "People Can Fly" },
  { title: "Outriders", studio: "People Can Fly" },
  { title: "Serious Sam Collection", studio: "Croteam" },

  // --- FIGHTING & MARTIAL ARTS (EXTENDED) ---
  { title: "Mortal Kombat XL", studio: "NetherRealm" },
  { title: "Injustice: Gods Among Us", studio: "NetherRealm" },
  { title: "Tekken 7: Definitive Edition", studio: "Bandai Namco" },
  { title: "SoulCalibur VI", studio: "Project Soul" },
  { title: "Fighting EX Layer", studio: "Arika" },
  { title: "The King of Fighters XIV", studio: "SNK" },
  { title: "Samurai Shodown V Perfect", studio: "SNK" },
  { title: "Garou: Mark of the Wolves", studio: "SNK" },
  { title: "Dead or Alive 5 Last Round", studio: "Team Ninja" },
  { title: "Jump Force", studio: "Spike Chunsoft" },
  { title: "My Hero One's Justice", studio: "Byking" },
  { title: "My Hero One's Justice 2", studio: "Byking" },
  { title: "One Punch Man: A Hero Nobody Knows", studio: "Spike Chunsoft" },
  { title: "Saint Seiya: Soldiers' Soul", studio: "Dimps" },
  { title: "Dragon Ball Xenoverse", studio: "Dimps" },
  { title: "Dragon Ball Xenoverse 2", studio: "Dimps" },
  { title: "Gundam Versus", studio: "Bandai Namco" },
  { title: "Mobile Suit Gundam Extreme VS. Maxiboost ON", studio: "Bandai Namco" },

  // --- HORROR & SURVIVAL ---
  { title: "Alien: Isolation", studio: "Creative Assembly" },
  { title: "The Evil Within", studio: "Tango Gameworks" },
  { title: "The Evil Within 2", studio: "Tango Gameworks" },
  { title: "Resident Evil: Revelations", studio: "Capcom" },
  { title: "Resident Evil: Revelations 2", studio: "Capcom" },
  { title: "Resident Evil 4 (Original)", studio: "Capcom" },
  { title: "Resident Evil 5", studio: "Capcom" },
  { title: "Resident Evil 6", studio: "Capcom" },
  { title: "The Inpatient", studio: "Supermassive Games" },
  { title: "The Persistence", studio: "Firesprite" },
  { title: "Song of Horror", studio: "Protocol Games" },
  { title: "Visage", studio: "SadSquare Studio" },
  { title: "Madison", studio: "Bloodious Games" },
  { title: "Infliction: Extended Cut", studio: "Caustic Reality" },
  { title: "Blair Witch", studio: "Bloober Team" },
  { title: "Observer: System Redux", studio: "Bloober Team" },
  { title: "Daymare: 1998", studio: "Invader Studios" },
  { title: "Chernobylite", studio: "The Farm 51" },
  { title: "Terminator: Resistance", studio: "Teyon" },
  { title: "RoboCop: Rogue City (Cloud/Port)", studio: "Teyon" },

  // --- SPORTS & RACING ---
  { title: "Tony Hawk's Pro Skater 1+2", studio: "Vicarious Visions" },
  { title: "Skate 3 (via Cloud)", studio: "EA Black Box" },
  { title: "SnowRunner", studio: "Saber Interactive" },
  { title: "MudRunner", studio: "Saber Interactive" },
  { title: "Onrush", studio: "Codemasters" },
  { title: "Dirt Rally", studio: "Codemasters" },
  { title: "Dirt Rally 2.0", studio: "Codemasters" },
  { title: "Grid (2019)", studio: "Codemasters" },
  { title: "Grid Legends", studio: "Codemasters" },
  { title: "Project CARS", studio: "Slightly Mad Studios" },
  { title: "Project CARS 2", studio: "Slightly Mad Studios" },
  { title: "Driveclub", studio: "Evolution Studios" },
  { title: "Driveclub VR", studio: "Evolution Studios" },
  { title: "Need for Speed Rivals", studio: "Ghost Games" },
  { title: "Need for Speed (2015)", studio: "Ghost Games" },
  { title: "Need for Speed Payback", studio: "Ghost Games" },
  { title: "Burnout Paradise Remastered", studio: "Criterion Games" },
  { title: "Wipeout Omega Collection", studio: "Sony XDev" },
  { title: "Trackmania Turbo", studio: "Nadeo" },
  { title: "Hotshot Racing", studio: "Lucky Mountain" },

  // --- RPG & JRPG (FURTHER) ---
  { title: "Blue Reflection", studio: "Gust" },
  { title: "Blue Reflection: Second Light", studio: "Gust" },
  { title: "Atelier Ryza: Ever Darkness & the Secret Hideout", studio: "Gust" },
  { title: "Atelier Ryza 2: Lost Legends", studio: "Gust" },
  { title: "Atelier Ryza 3: Alchemist of the End", studio: "Gust" },
  { title: "Atelier Sophie: The Alchemist of the Mysterious Book", studio: "Gust" },
  { title: "Atelier Sophie 2", studio: "Gust" },
  { title: "Valkyria Chronicles Remastered", studio: "Sega" },
  { title: "Valkyria Chronicles 4", studio: "Sega" },
  { title: "The Legend of Heroes: Trails from Zero", studio: "Nihon Falcom" },
  { title: "The Legend of Heroes: Trails to Azure", studio: "Nihon Falcom" },
  { title: "The Legend of Heroes: Trails into Reverie", studio: "Nihon Falcom" },
  { title: "Trails of Cold Steel II", studio: "Nihon Falcom" },
  { title: "Trails of Cold Steel III", studio: "Nihon Falcom" },
  { title: "Trails of Cold Steel IV", studio: "Nihon Falcom" },
  { title: "Final Fantasy X/X-2 HD Remaster", studio: "Square Enix" },
  { title: "Final Fantasy XII: The Zodiac Age", studio: "Square Enix" },
  { title: "Final Fantasy XV", studio: "Square Enix" },
  { title: "World of Final Fantasy", studio: "Square Enix" },
  { title: "Kingdom Hearts HD 1.5 + 2.5 ReMIX", studio: "Square Enix" },
  { title: "Kingdom Hearts HD 2.8 Final Chapter Prologue", studio: "Square Enix" },
  { title: "Kingdom Hearts: Melody of Memory", studio: "Square Enix" },
  { title: "NieR: Automata Game of the YoRHa Edition", studio: "PlatinumGames" },
  { title: "Dragon Quest Builders", studio: "Square Enix" },
  { title: "Dragon Quest Builders 2", studio: "Square Enix" },
  { title: "Dragon Quest Heroes: The World Tree's Woe", studio: "Omega Force" },
  { title: "Dragon Quest Heroes II", studio: "Omega Force" },

  // --- OPEN WORLD & ADVENTURE ---
  { title: "Watch Dogs", studio: "Ubisoft" },
  { title: "Sleeping Dogs: Definitive Edition", studio: "United Front" },
  { title: "Just Cause 3", studio: "Avalanche Studios" },
  { title: "Just Cause 4", studio: "Avalanche Studios" },
  { title: "Mad Max", studio: "Avalanche Studios" },
  { title: "Far Cry 3 Classic Edition", studio: "Ubisoft" },
  { title: "Far Cry 4", studio: "Ubisoft" },
  { title: "Far Cry 5", studio: "Ubisoft" },
  { title: "Far Cry Primal", studio: "Ubisoft" },
  { title: "Far Cry New Dawn", studio: "Ubisoft" },
  { title: "Assassin's Creed IV: Black Flag", studio: "Ubisoft" },
  { title: "Assassin's Creed Rogue Remastered", studio: "Ubisoft" },
  { title: "Assassin's Creed Unity", studio: "Ubisoft" },
  { title: "Assassin's Creed Syndicate", studio: "Ubisoft" },
  { title: "Assassin's Creed The Ezio Collection", studio: "Ubisoft" },
  { title: "Assassin's Creed III Remastered", studio: "Ubisoft" },
  
  { title: "Tom Clancy's The Division", studio: "Ubisoft" },
  { title: "The Saboteur (via Cloud)", studio: "Pandemic" },
  { title: "Saints Row IV: Re-Elected", studio: "Volition" },
  { title: "Saints Row: Gat out of Hell", studio: "Volition" },
  { title: "Saints Row: The Third Remastered", studio: "Volition" },
  { title: "Mafia III", studio: "Hangar 13" },
  { title: "L.A. Noire", studio: "Team Bondi" },
  { title: "Red Dead Revolver", studio: "Rockstar" },
  { title: "Bully", studio: "Rockstar" },

  // --- INDIE & PUZZLE ---
  { title: "Tunic", studio: "Andrew Shouldice" },
  { title: "Deaths Door", studio: "Acid Nerve" },
  { title: "Hades", studio: "Supergiant Games" },
  { title: "Pyre", studio: "Supergiant Games" },
  { title: "Transistor", studio: "Supergiant Games" },
  { title: "Bastion", studio: "Supergiant Games" },
  { title: "Hollow Knight", studio: "Team Cherry" },
  { title: "Celeste", studio: "Extremely OK Games" },
  { title: "Shovel Knight: Treasure Trove", studio: "Yacht Club Games" },
  { title: "The Messenger", studio: "Sabotage Studio" },
  { title: "Sea of Stars", studio: "Sabotage Studio" },
  { title: "Dave the Diver", studio: "Mintrocket" },
  { title: "Cult of the Lamb", studio: "Massive Monster" },
  { title: "Outer Wilds", studio: "Mobius Digital" },
  { title: "Inside", studio: "Playdead" },
  { title: "Limbo", studio: "Playdead" },
  { title: "Little Nightmares", studio: "Tarsier Studios" },
  { title: "Little Nightmares II", studio: "Tarsier Studios" },
  { title: "Braid: Anniversary Edition", studio: "Thekla, Inc." },
  { title: "The Witness", studio: "Thekla, Inc." },
  { title: "Firewatch", studio: "Campo Santo" },
  { title: "Oxenfree", studio: "Night School Studio" },
  { title: "Oxenfree II: Lost Signals", studio: "Night School Studio" },
  { title: "Night in the Woods", studio: "Finji" },
  { title: "Stray", studio: "BlueTwelve Studio" },
  { title: "Untitled Goose Game", studio: "House House" },
  { title: "Fall Guys", studio: "Mediatonic" },
  { title: "Among Us", studio: "Innersloth" },
  { title: "Overcooked!", studio: "Ghost Town Games" },
  { title: "Overcooked! 2", studio: "Ghost Town Games" },
  { title: "Moving Out", studio: "SMG Studio" },
  { title: "Moving Out 2", studio: "SMG Studio" },
  { title: "Human Fall Flat", studio: "No Brakes Games" },
  { title: "Gang Beasts", studio: "Boneloaf" },
  { title: "Cuphead", studio: "Studio MDHR" },

  // --- STRATEGY & SIMULATION ---
  { title: "Cities: Skylines", studio: "Colossal Order" },
  { title: "Surviving Mars", studio: "Haemimont Games" },
  { title: "Tropico 5", studio: "Haemimont Games" },
  { title: "Tropico 6", studio: "Limbic Entertainment" },
  { title: "XCOM: Enemy Unknown", studio: "Firaxis" },
  { title: "XCOM 2", studio: "Firaxis" },
  { title: "Sid Meier's Civilization VI", studio: "Firaxis" },
  { title: "Desperados III", studio: "Mimimi Games" },
  { title: "Shadow Tactics: Blades of the Shogun", studio: "Mimimi Games" },
  { title: "Mutant Year Zero: Road to Eden", studio: "The Bearded Ladies" },
  { title: "Empire of Sin", studio: "Romero Games" },
  { title: "The Sims 4", studio: "Maxis" },
  { title: "Two Point Hospital", studio: "Two Point Studios" },
  { title: "Two Point Campus", studio: "Two Point Studios" },
  { title: "Jurassic World Evolution", studio: "Frontier Developments" },
  { title: "Jurassic World Evolution 2", studio: "Frontier Developments" },
  { title: "Planet Coaster", studio: "Frontier Developments" },
  { title: "Elite Dangerous", studio: "Frontier Developments" },
  { title: "Stellaris: Console Edition", studio: "Paradox Development Studio" },
  { title: "Frostpunk: Console Edition", studio: "11 bit studios" },
  { title: "Ancestors: The Humankind Odyssey", studio: "Panache Digital" },
  { title: "Ark: Survival Evolved", studio: "Studio Wildcard" },
  { title: "Conan Exiles", studio: "Funcom" },
  { title: "Subnautica", studio: "Unknown Worlds" },
  { title: "Subnautica: Below Zero", studio: "Unknown Worlds" },
  { title: "The Forest", studio: "Endnight Games" },
  { title: "Stranded Deep", studio: "Beam Team Games" },

  // --- JAPANESE ARCADE & VARIETY ---
  { title: "Yakuza 0", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza Kiwami", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza Kiwami 2", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza 3 Remastered", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza 4 Remastered", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza 5 Remastered", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza 6: The Song of Life", studio: "Ryu Ga Gotoku Studio" },
  { title: "Yakuza: Like a Dragon", studio: "Ryu Ga Gotoku Studio" },
  { title: "Judgment", studio: "Ryu Ga Gotoku Studio" },
  { title: "Lost Judgment", studio: "Ryu Ga Gotoku Studio" },
  { title: "Like a Dragon: Ishin!", studio: "Ryu Ga Gotoku Studio" },
  { title: "Fist of the North Star: Lost Paradise", studio: "Ryu Ga Gotoku Studio" },
  { title: "Shenmue I & II", studio: "Sega" },
  { title: "Shenmue III", studio: "Ys Net" },
  { title: "Catherine: Full Body", studio: "Atlus" },
  { title: "Persona 5 Royal", studio: "Atlus" },
  { title: "Persona 5 Strikers", studio: "Omega Force" },
  { title: "Persona 4 Golden", studio: "Atlus" },
  { title: "Persona 3 Portable", studio: "Atlus" },
  { title: "Persona 3 Reload (Port)", studio: "Atlus" },
  { title: "Shin Megami Tensei III: Nocturne HD", studio: "Atlus" },
  { title: "Soul Hackers 2", studio: "Atlus" },
  { title: "Granblue Fantasy: Versus", studio: "Arc System Works" },
  { title: "Granblue Fantasy: Versus Rising", studio: "Arc System Works" },
  { title: "BlazBlue: Central Fiction", studio: "Arc System Works" },
  { title: "Guilty Gear Xrd -REVELATOR-", studio: "Arc System Works" },
  { title: "Guilty Gear Strive", studio: "Arc System Works" },
  { title: "Under Night In-Birth Exe:Late[cl-r]", studio: "French-Bread" },
  { title: "Melty Blood: Type Lumina", studio: "French-Bread" },
  { title: "Dragon Ball FighterZ", studio: "Arc System Works" },

  // --- ADDITIONAL VARIETY ---
  { title: "No Man's Sky", studio: "Hello Games" },
  { title: "Warframe", studio: "Digital Extremes" },
  { title: "Destiny", studio: "Bungie" },
  { title: "Destiny 2", studio: "Bungie" },
  { title: "The Elder Scrolls Online", studio: "ZeniMax Online" },
  { title: "Final Fantasy XIV: Online", studio: "Square Enix" },
  { title: "Genshin Impact", studio: "HoYoverse" },
  { title: "Honkai: Star Rail (Cloud/Port)", studio: "HoYoverse" },
  { title: "Tower of Fantasy", studio: "Hotta Studio" },
  { title: "MultiVersus", studio: "Player First Games" },
  { title: "Rocket League", studio: "Psyonix" },
  { title: "Dead by Daylight", studio: "Behaviour Interactive" },
  { title: "Friday the 13th: The Game", studio: "IllFonic" },
  { title: "Predator: Hunting Grounds", studio: "IllFonic" },
  { title: "Hunt: Showdown", studio: "Crytek" },
  { title: "DayZ", studio: "Bohemia Interactive" },
  { title: "Rust: Console Edition", studio: "Facepunch Studios" },
  { title: "Minecraft: PlayStation 4 Edition", studio: "Mojang" },
  { title: "Terraria", studio: "Re-Logic" },
  { title: "Stardew Valley", studio: "ConcernedApe" },
  { title: "Slime Rancher", studio: "Monomi Park" },
  { title: "PowerWash Simulator", studio: "FuturLab" },
  { title: "House Flipper", studio: "Empyrean" },
  { title: "Car Mechanic Simulator", studio: "Red Dot Games" },
  { title: "Gas Station Simulator", studio: "DRAGO entertainment" },
  { title: "Cooking Simulator", studio: "Big Cheese Studio" },
  { title: "Thief Simulator", studio: "Noble Muffins" },
  { title: "Construction Simulator", studio: "weltenbauer." },
  { title: "Bus Simulator 21", studio: "stillalive studios" },
  { title: "Farming Simulator 19", studio: "Giants Software" },
  { title: "Farming Simulator 22", studio: "Giants Software" },
  { title: "Train Sim World 3", studio: "Dovetail Games" },
  { title: "Euro Truck Simulator 2 (via Remote/Port)", studio: "SCS Software" },
  { title: "Elite Dangerous: Horizons", studio: "Frontier Developments" },

  // --- PLATFORMERS & RETRO-STYLE ---
  { title: "Crash Bandicoot 4: It's About Time", studio: "Toys for Bob" },
  { title: "Crash Team Racing Nitro-Fueled", studio: "Beenox" },
  { title: "Spyro Reignited Trilogy", studio: "Toys for Bob" },
  { title: "Ratchet & Clank: Rift Apart (Cloud/Port)", studio: "Insomniac" },
  { title: "Knack", studio: "Japan Studio" },
  { title: "Knack II", studio: "Japan Studio" },
  { title: "Sackboy: A Big Adventure", studio: "Sumo Digital" },
  { title: "LittleBigPlanet 3", studio: "Sumo Digital" },
  { title: "Tearaway Unfolded", studio: "Media Molecule" },
  { title: "Dreams", studio: "Media Molecule" },
  { title: "Concrete Genie", studio: "Pixelopus" },
  { title: "A Hat in Time", studio: "Gears for Breakfast" },
  { title: "Yooka-Laylee", studio: "Playtonic Games" },
  { title: "Yooka-Laylee and the Impossible Lair", studio: "Playtonic Games" },
  { title: "New Super Lucky's Tale", studio: "Playful Studios" },
  { title: "Psychonauts 2", studio: "Double Fine" },
  { title: "Rayman Legends", studio: "Ubisoft" },
  { title: "Sonic Mania", studio: "Christian Whitehead" },
  { title: "Sonic Forces", studio: "Sonic Team" },
  { title: "Wonder Boy: The Dragon's Trap", studio: "Lizardcube" },
  { title: "Streets of Rage 4", studio: "Dotemu" },
  { title: "Teenage Mutant Ninja Turtles: Shredder's Revenge", studio: "Tribute Games" },
  { title: "River City Girls", studio: "WayForward" },
  { title: "River City Girls 2", studio: "WayForward" },
  { title: "Bloodstained: Ritual of the Night", studio: "ArtPlay" },
  { title: "Bloodstained: Curse of the Moon", studio: "Inti Creates" },
  { title: "Bloodstained: Curse of the Moon 2", studio: "Inti Creates" },
  { title: "Blasphemous", studio: "The Game Kitchen" },
  { title: "Salt and Sanctuary", studio: "Ska Studios" },
  { title: "Salt and Sacrifice", studio: "Ska Studios" },
  { title: "Ender Lilies: Quietus of the Knights", studio: "Adglobe" },

  // --- FINAL BATCH ---
  { title: "Outer Banks", studio: "Netflix Games" },
  { title: "The Dark Pictures Anthology: Man of Medan", studio: "Supermassive Games" },
  { title: "The Dark Pictures Anthology: Little Hope", studio: "Supermassive Games" },
  { title: "The Dark Pictures Anthology: House of Ashes", studio: "Supermassive Games" },
  { title: "The Dark Pictures Anthology: The Devil in Me", studio: "Supermassive Games" },
  { title: "Until Dawn", studio: "Supermassive Games" },
  { title: "The Quarry", studio: "Supermassive Games" },
  { title: "Hidden Agenda", studio: "Supermassive Games" },
  { title: "Erica", studio: "Flavourworks" },
  { title: "Detroit: Become Human", studio: "Quantic Dream" },
  { title: "Life is Strange", studio: "Dontnod" },
  { title: "Life is Strange: Before the Storm", studio: "Deck Nine" },
  { title: "Life is Strange 2", studio: "Dontnod" },
  { title: "Life is Strange: True Colors", studio: "Deck Nine" },
  { title: "Tell Me Why", studio: "Dontnod" },
  { title: "Twin Mirror", studio: "Dontnod" },
  { title: "Vampyr", studio: "Dontnod" },
  { title: "The Council", studio: "Big Bad Wolf" },
  { title: "A Plague Tale: Innocence", studio: "Asobo Studio" },
  { title: "A Plague Tale: Requiem (via Cloud)", studio: "Asobo Studio" },
  { title: "Hellblade: Senua's Sacrifice", studio: "Ninja Theory" },
  { title: "Kena: Bridge of Spirits", studio: "Ember Lab" },
  { title: "Sifu", studio: "Sloclap" },
  { title: "Absolver", studio: "Sloclap" },
  { title: "Solar Ash", studio: "Heart Machine" },
  { title: "Hyper Light Drifter", studio: "Heart Machine" },
  { title: "Katana ZERO", studio: "Askiisoft" },
  { title: "My Friend Pedro", studio: "DeadToast" },
  { title: "Ghostrunner", studio: "One More Level" },
  { title: "Ghostrunner 2", studio: "One More Level" },
  { title: "Neon White", studio: "Angel Matrix" },
  { title: "Deathloop (Port)", studio: "Arkane" },
  { title: "Ghostwire: Tokyo (Port)", studio: "Tango Gameworks" },
  { title: "Forspoken (Port)", studio: "Luminous Productions" },
  { title: "Atomic Heart (Port)", studio: "Mundfish" },
  // --- ACTION & ADVENTURE COLLECTIONS ---
  { title: "Uncharted: The Nathan Drake Collection", studio: "Bluepoint Games" },
  { title: "The Last of Us Remastered", studio: "Naughty Dog" },
  { title: "Bioshock: The Collection", studio: "Blind Squirrel" },
  { title: "Batman: Return to Arkham", studio: "Virtuos" },
  { title: "Borderlands: The Legendary Collection", studio: "Gearbox" },
  { title: "Kingdom Hearts All-In-One Package", studio: "Square Enix" },
  { title: "Devil May Cry HD Collection", studio: "Capcom" },
  { title: "Castlevania Anniversary Collection", studio: "Konami" },
  { title: "Contra Anniversary Collection", studio: "Konami" },
  { title: "Mega Man Zero/ZX Legacy Collection", studio: "Capcom" },
  { title: "Street Fighter 30th Anniversary Collection", studio: "Digital Eclipse" },
  { title: "SNK 40th Anniversary Collection", studio: "Digital Eclipse" },
  { title: "Genesis Classics", studio: "Sega" },
  { title: "Jak and Daxter Bundle", studio: "Naughty Dog" },
  { title: "Ratchet & Clank (2016)", studio: "Insomniac Games" },

  // --- FIGHTING & COMBAT (EXTENDED) ---
  { title: "UFC 2", studio: "EA Sports" },
  { title: "UFC (2014)", studio: "EA Sports" },
  { title: "Mortal Kombat X", studio: "NetherRealm" },
  { title: "Tekken 6 (via Cloud)", studio: "Bandai Namco" },
  { title: "SoulCalibur V (via Cloud)", studio: "Project Soul" },
  { title: "Dead or Alive 5 Ultimate", studio: "Team Ninja" },
  { title: "The King of Fighters XIV: Ultimate Edition", studio: "SNK" },
  { title: "The King of Fighters 2002 Unlimited Match", studio: "SNK" },
  { title: "The King of Fighters '98 Ultimate Match", studio: "SNK" },
  { title: "Garou: Mark of the Wolves", studio: "SNK" },
  { title: "Fatal Fury Special", studio: "SNK" },
  { title: "Art of Fighting Anthology", studio: "SNK" },
  { title: "World Heroes Anthology", studio: "SNK" },
  { title: "Samurai Shodown Neogeo Collection", studio: "Digital Eclipse" },
  { title: "Guilty Gear Xrd REV 2", studio: "Arc System Works" },
  { title: "Guilty Gear Accent Core Plus R", studio: "Arc System Works" },
  { title: "Under Night In-Birth Exe:Late[st]", studio: "French-Bread" },
  { title: "Arcana Heart 3: Love Max!!!!!", studio: "Examu" },
  { title: "Skullgirls 2nd Encore", studio: "Lab Zero Games" },
  { title: "Nitroplus Blasterz: Heroines Infinite Duel", studio: "Examu" },

  // --- ANIME & JAPANESE ACTION ---
  { title: "Dragon Ball Z: Kakarot", studio: "CyberConnect2" },
  { title: "Naruto To Boruto: Shinobi Striker", studio: "Soleil" },
  { title: "Naruto Shippuden: Ultimate Ninja Storm Trilogy", studio: "CyberConnect2" },
  { title: "One Piece: Burning Blood", studio: "Spike Chunsoft" },
  { title: "One Piece World Seeker", studio: "Ganbarion" },
  { title: "Bleach: Brave Souls", studio: "KLab" },
  { title: "Attack on Titan", studio: "Omega Force" },
  { title: "Attack on Titan 2: Final Battle", studio: "Omega Force" },
  { title: "Berserk and the Band of the Hawk", studio: "Omega Force" },
  { title: "Sword Art Online: Hollow Realization", studio: "Aquria" },
  { title: "Sword Art Online: Fatal Bullet", studio: "Dimps" },
  { title: "Sword Art Online: Alicization Lycoris", studio: "Aquria" },
  { title: "Accel World vs. Sword Art Online", studio: "Artdink" },
  { title: "God Eater 2: Rage Burst", studio: "Shift" },
  { title: "God Eater 3", studio: "Marvelous" },
  { title: "Fate/Extella: The Umbral Star", studio: "Marvelous" },
  { title: "Fate/Extella Link", studio: "Marvelous" },
  { title: "Senran Kagura: Burst Re:Newal", studio: "Tamsoft" },
  { title: "Senran Kagura: Estival Versus", studio: "Tamsoft" },
  { title: "Senran Kagura: Peach Beach Splash", studio: "Tamsoft" },

  // --- OPEN WORLD & SHOOTERS ---
  { title: "Sniper Ghost Warrior Contracts", studio: "CI Games" },
  { title: "Sniper Ghost Warrior Contracts 2", studio: "CI Games" },
  { title: "Sniper Ghost Warrior 3", studio: "CI Games" },
  { title: "Generation Zero", studio: "Avalanche Studios" },
  { title: "Homefront: The Revolution", studio: "Dambuster Studios" },
  { title: "ELEX", studio: "Piranha Bytes" },
  { title: "ELEX II", studio: "Piranha Bytes" },
  { title: "Gothic 1 Remake (Planned)", studio: "Alkimia Interactive" },
  { title: "Risen", studio: "Piranha Bytes" },
  { title: "GreedFall: Gold Edition", studio: "Spiders" },
  { title: "The Technomancer", studio: "Spiders" },
  { title: "Bound by Flame", studio: "Spiders" },
  { title: "Outward", studio: "Nine Dots Studio" },
  { title: "Kingdom Come: Deliverance Royal Edition", studio: "Warhorse" },
  { title: "Vampyr", studio: "Dontnod" },
  { title: "Call of Cthulhu", studio: "Cyanide" },
  { title: "The Sinking City", studio: "Frogwares" },
  { title: "Sherlock Holmes: Crimes & Punishments", studio: "Frogwares" },
  { title: "Sherlock Holmes: The Devil's Daughter", studio: "Frogwares" },
  { title: "Sherlock Holmes Chapter One", studio: "Frogwares" },

  // --- HORROR & MYSTERY ---
  { title: "Agony", studio: "Madmind Studio" },
  { title: "Succubus", studio: "Madmind Studio" },
  { title: "The Medium", studio: "Bloober Team" },
  { title: "Blair Witch", studio: "Bloober Team" },
  { title: "Layers of Fear 2", studio: "Bloober Team" },
  { title: "Maid of Sker", studio: "Wales Interactive" },
  { title: "Don't Knock Twice", studio: "Wales Interactive" },
  { title: "Remothered: Tormented Fathers", studio: "Stormind Games" },
  { title: "Remothered: Broken Porcelain", studio: "Stormind Games" },
  { title: "The Beast Inside", studio: "Illusion Ray" },
  { title: "Fobia - St. Dinfna Hotel", studio: "Pulsatrix Studios" },
  { title: "Song of Horror", studio: "Protocol Games" },
  { title: "Tormented Souls", studio: "Dual Effect" },
  { title: "White Day: A Labyrinth Named School", studio: "Sonnori" },
  { title: "Forbidden Siren (PS2 Port)", studio: "Japan Studio" },
  { title: "Manhunt (PS2 Port)", studio: "Rockstar North" },
  { title: "The Warriors (PS2 Port)", studio: "Rockstar Toronto" },

  // --- SPORTS, RACING & SIMULATION ---
  { title: "WRC 10", studio: "KT Racing" },
  { title: "WRC 9", studio: "KT Racing" },
  { title: "WRC 8", studio: "KT Racing" },
  { title: "V-Rally 4", studio: "KT Racing" },
  { title: "FlatOut 4: Total Insanity", studio: "Kylotonn" },
  { title: "Monster Energy Supercross 5", studio: "Milestone" },
  { title: "MXGP 2021", studio: "Milestone" },
  { title: "Ride 3", studio: "Milestone" },
  { title: "Ride 2", studio: "Milestone" },
  { title: "Valentino Rossi: The Game", studio: "Milestone" },
  { title: "Sébastien Loeb Rally EVO", studio: "Milestone" },
  { title: "NASCAR Heat 5", studio: "704Games" },
  { title: "Tony Hawk's Pro Skater 5", studio: "Robomodo" },
  { title: "Skatebird", studio: "Glass Bottom Games" },
  { title: "OlliOlli World", studio: "Roll7" },
  { title: "OlliOlli2: Welcome to Olliwood", studio: "Roll7" },
  { title: "Laser League", studio: "Roll7" },
  { title: "Descenders", studio: "RageSquid" },
  { title: "Lonely Mountains: Downhill", studio: "Megagon Industries" },

  // --- INDIE, PUZZLE & STRATEGY ---
  { title: "Among Us", studio: "Innersloth" },
  { title: "Fall Guys: Ultimate Knockout", studio: "Mediatonic" },
  { title: "Gang Beasts", studio: "Boneloaf" },
  { title: "Human Fall Flat", studio: "No Brakes Games" },
  { title: "Rubber Bandits", studio: "Flashbulb" },
  { title: "Golf With Your Friends", studio: "Blacklight Interactive" },
  { title: "Party Animals (via Cloud)", studio: "Recreate Games" },
  { title: "The Jackbox Party Pack 8", studio: "Jackbox Games" },
  { title: "The Jackbox Party Pack 7", studio: "Jackbox Games" },
  { title: "Ultimate Chicken Horse", studio: "Clever Endeavour" },
  { title: "Move or Die", studio: "Those Awesome Guys" },
  { title: "Stick Fight: The Game", studio: "Landfall" },
  { title: "Totally Accurate Battle Simulator", studio: "Landfall" },
  { title: "Braid Anniversary Edition", studio: "Thekla, Inc." },
  { title: "FEZ", studio: "Polytron" },
  { title: "Super Meat Boy Forever", studio: "Team Meat" },
  { title: "Shovel Knight: Shovel of Hope", studio: "Yacht Club" },
  { title: "Shovel Knight: Specter of Torment", studio: "Yacht Club" },
  { title: "Messenger, The", studio: "Sabotage Studio" },
  { title: "Sea of Stars", studio: "Sabotage Studio" },

  // --- RPG, TACTICS & CARDS ---
  { title: "Slay the Spire", studio: "MegaCrit" },
  { title: "Monster Train First Class", studio: "Shiny Shoe" },
  { title: "Inscryption", studio: "Daniel Mullins" },
  { title: "Balatro", studio: "LocalThunk" },
  { title: "Hand of Fate 2", studio: "Defiant Development" },
  { title: "Gwent: The Witcher Card Game", studio: "CD Projekt Red" },
  { title: "Thronebreaker: The Witcher Tales", studio: "CD Projekt Red" },
  { title: "Darkest Dungeon", studio: "Red Hook Studios" },
  { title: "Darkest Dungeon II", studio: "Red Hook Studios" },
  { title: "Iratus: Lord of the Dead", studio: "Unfrozen" },
  { title: "Battle Chasers: Nightwar", studio: "Airship Syndicate" },
  { title: "Ruined King: A League of Legends Story", studio: "Airship Syndicate" },
  { title: "Vambrace: Cold Soul", studio: "Devespresso Games" },
  { title: "The Coma: Recut", studio: "Devespresso Games" },
  { title: "The Coma 2: Vicious Sisters", studio: "Devespresso Games" },

  // --- SIMULATORS & SPECIALTY ---
  { title: "Goat Simulator", studio: "Coffee Stain" },
  { title: "Goat Simulator 3 (Port)", studio: "Coffee Stain" },
  { title: "I Am Bread", studio: "Bossa Studios" },
  { title: "Surgeon Simulator: A&E Anniversary Edition", studio: "Bossa Studios" },
  { title: "Surgeon Simulator 2", studio: "Bossa Studios" },
  { title: "Untitled Goose Game", studio: "House House" },
  { title: "Donut County", studio: "Ben Esposito" },
  { title: "PowerWash Simulator", studio: "FuturLab" },
  { title: "Lawn Mowing Simulator", studio: "Skyhook Games" },
  { title: "Ship Graveyard Simulator", studio: "Games Incubator" },
  { title: "Barn Finders", studio: "Duality Games" },
  { title: "Drug Dealer Simulator", studio: "Byterunners" },
  { title: "Internet Cafe Simulator", studio: "Cheesecake Dev" },
  { title: "Streamer Daily", studio: "All In! Games" },
  { title: "PC Building Simulator", studio: "Claudiu Kiss" },
  { title: "Car Mechanic Simulator 2021", studio: "Red Dot Games" },
  { title: "Gold Rush: The Game", studio: "Code Horizon" },
  { title: "Discovery: Gold Rush", studio: "Discovery" },
  { title: "Alaska: The Last Frontier", studio: "Discovery" },

  // --- PLAYSTATION VR ESSENTIALS (Playable without VR in some modes) ---
  { title: "Resident Evil 7: Biohazard VR", studio: "Capcom" },
  { title: "Astro Bot Rescue Mission", studio: "Japan Studio" },
  { title: "Blood & Truth", studio: "London Studio" },
  { title: "Moss", studio: "Polyarc" },
  { title: "Moss: Book II", studio: "Polyarc" },
  { title: "Beat Saber", studio: "Beat Games" },
  { title: "Superhot VR", studio: "Superhot Team" },
  { title: "Tetris Effect: Connected", studio: "Monstars" },
  { title: "Rez Infinite", studio: "Monstars" },
  { title: "Thumper", studio: "Drool" },
  { title: "Star Trek: Bridge Crew", studio: "Red Storm" },
  { title: "Farpoint", studio: "Impulse Gear" },
  { title: "Firewall Zero Hour", studio: "First Contact" },
  { title: "Iron Man VR", studio: "Camouflaj" },
  { title: "The Walking Dead: Saints & Sinners", studio: "Skydance Interactive" },

  // --- MISC & CLASSICS ---
  { title: "Pac-Man Championship Edition 2", studio: "Bandai Namco" },
  { title: "Galaga Edition", studio: "Bandai Namco" },
  { title: "Dig Dug", studio: "Bandai Namco" },
  { title: "Katari Damacy Reroll", studio: "Bandai Namco" },
  { title: "Little Nightmares", studio: "Tarsier Studios" },
  { title: "Little Nightmares II", studio: "Tarsier Studios" },
  { title: "Very Little Nightmares (Port)", studio: "Tarsier Studios" },
  { title: "Telling Lies", studio: "Annapurna Interactive" },
  { title: "Her Story", studio: "Sam Barlow" },
  { title: "Immortality", studio: "Half Mermaid" },
  { title: "12 Minutes", studio: "Annapurna Interactive" },
  { title: "What Remains of Edith Finch", studio: "Giant Sparrow" },
  { title: "Unfinished Swan, The", studio: "Giant Sparrow" },
  { title: "Gone Home", studio: "Fullbright" },
  { title: "Tacoma", studio: "Fullbright" },
  { title: "Everybody's Gone to the Rapture", studio: "The Chinese Room" },
  { title: "Soma", studio: "Frictional Games" },
  { title: "Amnesia: Rebirth", studio: "Frictional Games" },
  { title: "Amnesia: The Bunker", studio: "Frictional Games" },
  // --- NBA 2K SERIES ---
  { title: "NBA 2K14", studio: "Visual Concepts" },
  { title: "NBA 2K15", studio: "Visual Concepts" },
  { title: "NBA 2K16", studio: "Visual Concepts" },
  { title: "NBA 2K17", studio: "Visual Concepts" },
  { title: "NBA 2K18", studio: "Visual Concepts" },
  { title: "NBA 2K19", studio: "Visual Concepts" },
  { title: "NBA 2K20", studio: "Visual Concepts" },
  { title: "NBA 2K21", studio: "Visual Concepts" },
  { title: "NBA 2K22", studio: "Visual Concepts" },
  { title: "NBA 2K23", studio: "Visual Concepts" },
  { title: "NBA 2K24", studio: "Visual Concepts" },
  { title: "NBA 2K Playgrounds 2", studio: "Saber Interactive" },

  // --- FIFA SERIES (EA SPORTS FC) ---
  { title: "FIFA 14", studio: "EA Sports" },
  { title: "FIFA 15", studio: "EA Sports" },
  { title: "FIFA 16", studio: "EA Sports" },
  { title: "FIFA 17", studio: "EA Sports" },
  { title: "FIFA 18", studio: "EA Sports" },
  { title: "FIFA 19", studio: "EA Sports" },
  { title: "FIFA 20", studio: "EA Sports" },
  { title: "FIFA 21", studio: "EA Sports" },
  { title: "FIFA 22", studio: "EA Sports" },
  { title: "FIFA 23", studio: "EA Sports" },
  { title: "EA Sports FC 24", studio: "EA Sports" },
  { title: "EA Sports FC 25", studio: "EA Sports" },
  { title: "FIFA Street", studio: "EA Sports" },

  // --- UFC & MMA SERIES ---
  { title: "EA Sports UFC", studio: "EA Canada" },
  { title: "EA Sports UFC 2", studio: "EA Canada" },
  { title: "EA Sports UFC 3", studio: "EA Canada" },
  { title: "EA Sports UFC 4", studio: "EA Canada" },
  { title: "EA Sports UFC 5", studio: "EA Canada" },
  // --- MODERN WARFARE SERIES ---
  { title: "Call of Duty: Modern Warfare (2019)", studio: "Infinity Ward" },
  { title: "Call of Duty: Modern Warfare II (2022)", studio: "Infinity Ward" },
  { title: "Call of Duty: Modern Warfare III (2023)", studio: "Sledgehammer Games" },
  { title: "Call of Duty: Modern Warfare Remastered", studio: "Raven Software" },
  { title: "Call of Duty: Modern Warfare 2 Campaign Remastered", studio: "Beenox" },

  // --- BLACK OPS SERIES ---
  { title: "Call of Duty: Black Ops III", studio: "Treyarch" },
  { title: "Call of Duty: Black Ops 4", studio: "Treyarch" },
  { title: "Call of Duty: Black Ops Cold War", studio: "Treyarch" },
  { title: "Call of Duty: Black Ops 6", studio: "Treyarch" },

  // --- STANDALONE & OTHER ---
  { title: "Call of Duty: Ghosts", studio: "Infinity Ward" },
  { title: "Call of Duty: Advanced Warfare", studio: "Sledgehammer Games" },
  { title: "Call of Duty: Infinite Warfare", studio: "Infinity Ward" },
  { title: "Call of Duty: WWII", studio: "Sledgehammer Games" },
  { title: "Call of Duty: Vanguard", studio: "Sledgehammer Games" },

  // --- FREE TO PLAY ---
  { title: "Call of Duty: Warzone", studio: "Raven Software" },
  { title: "For Honor", studio: "Ubisoft Montreal" },

  // --- CONSOLES & HARDWARE ---
  { title: "PlayStation 5 (Disc Edition)", studio: "Sony Interactive Entertainment", type: "Console" },
  { title: "PlayStation 5 (Digital Edition)", studio: "Sony Interactive Entertainment", type: "Console" },
  { title: "PlayStation 4 Slim", studio: "Sony Interactive Entertainment", type: "Console" },
  { title: "PlayStation 4 Pro", studio: "Sony Interactive Entertainment", type: "Console" },
  { title: "PlayStation 4 (Original)", studio: "Sony Interactive Entertainment", type: "Console" },
  { title: "PlayStation 3 Super Slim", studio: "Sony Interactive Entertainment", type: "Console" },
  { title: "MacBook Pro (Early 2015)", studio: "Apple", type: "Console" }, // Added for your dev setup

  // --- ACCESSORIES & GEAR ---
  { title: "DualSense Wireless Controller", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "DualShock 4 Wireless Controller", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "DualShock 3 Wireless Controller", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "PS5 Media Remote", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "Pulse 3D Wireless Headset", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "PlayStation VR2", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "PS4 Vertical Stand", studio: "Sony Interactive Entertainment", type: "Accessory" },
  { title: "HDMI 2.1 High Speed Cable", studio: "Generic", type: "Accessory" },
  // --- PROTECTION & MAINTENANCE ---
  { title: "DualShock 4 Silicon Case Cover", studio: "Generic", type: "Accessory" },
  { title: "DualSense Silicon Case Cover", studio: "Generic", type: "Accessory" },
  { title: "DualShock 4 Replacement Trigger Springs", studio: "Generic", type: "Accessory" },
  { title: "Analog Stick Drift Repair Kit", studio: "Generic", type: "Accessory" },
  { title: "Thumbstick Grip Caps (Pair)", studio: "Generic", type: "Accessory" },
  { title: "Console Dust Cover (Anti-Dust)", studio: "Generic", type: "Accessory" }


];

